CREATE TABLE "CAR" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "LICENSE_PLATE" VARCHAR(255),
    "BRAND" VARCHAR(255),
    "MODEL" VARCHAR(255),
    "PRICE_PER_DAY" INTEGER
);

CREATE TABLE "CUSTOMER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FULL_NAME" VARCHAR(255),
    "ADDRESS" VARCHAR(255),
    "PHONE_NUMBER" VARCHAR(255)
);

CREATE TABLE "LEASE" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CAR_ID" BIGINT REFERENCES CAR (ID),
    "CUSTOMER_ID" BIGINT REFERENCES CUSTOMER (ID),
    "PRICE" INTEGER,
    "START_TIME" DATE,
    "EXPECTED_END_TIME" DATE,
    "REAL_END_TIME" DATE
);

INSERT INTO CAR(LICENSE_PLATE, BRAND, MODEL, PRICE_PER_DAY) VALUES ('BA-123AA','BMW', 'X3', 123);
INSERT INTO CAR(LICENSE_PLATE, BRAND, MODEL, PRICE_PER_DAY) VALUES ('BA-100GA','Audi', 'Q8', 100);
INSERT INTO CAR(LICENSE_PLATE, BRAND, MODEL, PRICE_PER_DAY) VALUES ('BA-050FA','Citroen', 'C3', 50);
INSERT INTO CAR(LICENSE_PLATE, BRAND, MODEL, PRICE_PER_DAY) VALUES ('BA-070FF','BMW', 'M3', 150);

INSERT INTO CUSTOMER(FULL_NAME, ADDRESS, PHONE_NUMBER) VALUES ('Ferko Mrkvicka', 'Mlynska 25, Bratislava', '+421 9xx xxx xxx');
INSERT INTO CUSTOMER(FULL_NAME, ADDRESS, PHONE_NUMBER) VALUES ('Aneta Mala', 'Okruzna 4, Zilina', '+421 9xx xxx xxx');
INSERT INTO CUSTOMER(FULL_NAME, ADDRESS, PHONE_NUMBER) VALUES ('Jan Sidor', 'Cejl 13, Brno', '+420 9xx xxx xxx');
INSERT INTO CUSTOMER(FULL_NAME, ADDRESS, PHONE_NUMBER) VALUES ('Anna Plocha', 'Rovna 15, Bratislava', '+421 9xx xxx xxx');

INSERT INTO LEASE(CAR_ID, CUSTOMER_ID, PRICE, START_TIME, EXPECTED_END_TIME, REAL_END_TIME) VALUES (1, 1, 123, '2015-12-17', '2015-12-18', '2015-12-19');
